### ISSUE TITLE
server-side rendering support

### ISSUE THREAD

**Issue by FranckFreiburger** [lukaszflorczak/vue-agile#19]
It seems that vue-agile is not compatible with SSR.

When the server is rendering the page, I get the following error:
```
ReferenceError: window is not defined
    at ...\node_modules\vue-agile\dist\vue-agile.min.js:1:1
```

**Comment by FranckFreiburger** [comment]
however, everything works fine if I use the non-dist version: `import VueAgile from 'vue-agile/src/Agile.vue'`

**Comment by lukaszflorczak** [comment]
Thank you for issue. I don't have access to my computer this week, but I'll check it as soon as possible in the next.

**Comment by ashield** [comment]
@lukaszflorczak have you had a chance to look at this?

**Comment by lukaszflorczak** [comment]
Not yet, but I plan to do it today. Regards!

**Comment by lukaszflorczak** [comment]
@ashield, @FranckFreiburger 

I'm not very familiar with SSR, but I tried to look it closer. So, I'm not sure, but probably vue-agile might work only on the client side, because the plugin use elements specified for browsers only (like `window`, `document` etc.). In nuxt documentation I found:
- https://nuxtjs.org/guide/plugins#client-side-only
- https://nuxtjs.org/faq/window-document-undefined

Have you tried it?

**Comment by ashield** [comment]
@lukaszflorczak I had tried both of these things with no luck.

I have however just got this to work with [nuxt-v1.0.0-rc7)](https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0-rc7) which came out today.

Using https://nuxtjs.org/guide/plugins#client-side-only in combination with https://github.com/nuxt/nuxt.js/blob/dev/examples/no-ssr/pages/index.vue allows vue-agile to render correctly without any errors.

Thanks for looking into this!
