### ISSUE TITLE
Numbers and options object with nuxt

### ISSUE THREAD

**Issue by sainf** [lukaszflorczak/vue-agile#51]
I'm trying to use options as object and the agile does not accept the integers "autoplaySpeed, speed, etc.." 

`<agile :options="options">`

But using as inline option works fine.

`<agile :autoplaySpeed="8000" :autoplay="true">`

basic git to test: "https://github.com/sainf/nuxt-agile-bug"

**Comment by lukaszflorczak** [comment]
I will try to check it out this week.

PS. I apologize for the long response time, but I have not been available recently.

**Comment by lq782655835** [comment]
I also get this problem rencently

**Comment by lukaszflorczak** [comment]
Fixed in the upcoming `v1.0.0` version.

PS. I'm sorry for such a long absence. By the way, I would like to inform you that I'm finishing work on a new version of vue-agile, which has a completely refactored code, many new features, examples and documentation. I'll be grateful for checking that when the new version is released.
