### ISSUE TITLE
have trouble with displaying carousel

### ISSUE THREAD

**Issue by adFedorovich** [lukaszflorczak/vue-agile#52]
![](https://user-images.githubusercontent.com/15676325/35012834-3d42e2a6-fb1c-11e7-9cc3-9eea535f7c91.png)
I can not to put carousel to the right side of flexible wrapper

**Comment by lukaszflorczak** [comment]
I'll check it

**Comment by stevepop** [comment]
I have a slightly similar issue although I can display the Carousel but the arrows and buttons and not properly aligned and I am having to add extra CSS even to make the examples to work as seen. I see the issue has been opened since January. I guess the Author is quite busy. This is a good Vue plugin, it will be a shame if people are discouraged from using it because of time taken to respond to issues.

**Comment by lukaszflorczak** [comment]
Not confirmed in upcoming `v1.0` version.
