### ISSUE TITLE
Error "Failed to mount component: template or render function not defined."

### ISSUE THREAD

**Issue by HamHamFonFon** [lukaszflorczak/vue-agile#68]
Hello,

I make my first VueJs component and i'm trying a simple slider but i have thos error : 

```
[Vue warn]: Failed to mount component: template or render function not defined.
found in
---> <Agile>
       <App> at /src/App.vue

         <Root>
```
I put my code on this codesansbox : https://codesandbox.io/s/zx644v98wx
(or https://codesandbox.io/s/ly0j2o97pz based on your scripts in "demo" directory).

Thank you

**Comment by p1n5u** [comment]
Hi,

I've tested your code in the sandbox and like you said it is not working because you don't register the component correctly. You have two possibilities to fix your issue. 

The first one is to target the component correctly in your import. To do that you have to adapt the path like the following example in your `Homepage/components/Slider.vue` on line 12:
`import Agile from "vue-agile/dist/Agile"` 
here the sandbox for the first solution: https://codesandbox.io/s/p5w62v4j7j

The second way is to register vue-agile as plugin in the `main.js`. To do that you just need to add the following lines before you create your vue app (`new Vue({...})`):
```
import Agile from 'vue-agile'
Vue.use(Agile)
```
here the sandbox for the second solution: https://codesandbox.io/s/2x75oyqr5y

**Comment by HamHamFonFon** [comment]
Thank you for the fix. I continue to understand how VueJs works :)
